name: analysis
channels:
    - conda-forge
dependencies:
    - numpy==1.16.4
    - uproot
    - tensorflow
    - keras
    - xrootd
    - scikit-learn
    - matplotlib
    - tqdm
    - pip
    - pip:
      - jupyter-book
      - torch-scatter==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
      - torch-sparse==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
      - torch-cluster==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
      - torch-spline-conv==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
      - torch-geometric
