name: analysis
channels:
    - conda-forge
dependencies:
    - numpy==1.16.4
    - uproot
    - tensorflow
    - keras
    - xrootd
    - scikit-learn
    - matplotlib
    - tqdm
    - pip
    - pip:
      - jupyter-book
