name: analysis
channels:
    - conda-forge
dependencies:
    - uproot
    - keras
    - tensorflow
    - xrootd
    - scikit-learn
    - matplotlib
    - numpy
    - pip
    - pip:
      - jupyter-book
